# Generated by Django 5.0.2 on 2024-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='leksiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('rasm', models.ImageField(upload_to='rasm/images')),
                ('text', models.TextField()),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
