# Generated by Django 5.0.2 on 2024-05-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='rasm/images')),
                ('text', models.TextField()),
                ('narxi', models.IntegerField()),
            ],
        ),
    ]
