# Generated by Django 5.0.2 on 2024-05-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rasmlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=222)),
                ('text', models.TextField()),
                ('subject', models.CharField(max_length=777)),
                ('ismi', models.CharField(max_length=300)),
            ],
        ),
    ]
